# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

      - run: |
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

      - run:
          name: Deploy Datastore Consumer
          command: gcloud functions deploy "datastore-consume" --entry-point "ds_consume" --memory 128MB
            --region us-central1 --runtime python37 --trigger-topic "datahose-ds" --source "./functions/datastore"

      - run:
          name: Deploy Telegram Notifier
          command: gcloud functions deploy "telegram-consume" --entry-point "telegram_send" --memory 128MB
            --region us-central1 --runtime python37 --trigger-topic "notifications" --source "./functions/telegram"

      - run:
          name: Deploy Dispatcher
          command: gcloud functions deploy "datahose" --entry-point "dispatch" --memory 128MB
            --region us-central1 --runtime python37 --trigger-http --source "./functions/dispatch"
